name: shellot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    # Core dependencies
    - pathlib>=2.3.0
    - typing>=3.7.4
    - importlib-metadata>=4.11.0
    
    # Testing dependencies
    - pytest>=7.0.0
    - pytest-cov>=3.0.0
    - pytest-mock>=3.7.0
    
    # Development dependencies
    - black>=22.0.0
    - isort>=5.10.0
    - flake8>=4.0.0
    - mypy>=0.950
    
    # Optional dependencies
    - pyyaml>=6.0.0
    - colorama>=0.4.4
    - rich>=12.0.0

variables:
  PYTHONPATH: $PREFIX/lib/python3.9/site-packages